=== tests/cases/conformance/statements/tryStatements/invalidTryStatements2.ts ===
function fn() {
>fn : () => void

    catch(x) { } // error missing try
>x : any
>类型别名 :=> 任意

    finally { } // potential error; can be absorbed by the 'catch'

    try { }; // error missing finally
}

function fn2() {
>fn2 : () => void

    finally { } // error missing try
    catch (x) { } // error missing try
>x : any
>类型别名 :=> 任意
    
    try { } finally { } // statement is here, so the 'catch' clause above doesn't absorb errors from the 'finally' clause below

    finally { } // error missing try
    
    catch (x) { } // error missing try
>x : any
>类型别名 :=> 任意

    try { } catch () { } // error missing catch binding
> : any
>类型别名 :=> 任意
}
